### PR TITLE
Support for synchronous events

### PR DESCRIPTION
**Pull request by tomcw**
PR for #612.

Switched Mockingboard/6522 Timer interrupts & Mousecard's VBlank interrupt to use synchronous events.
This is a linked-list of ordered timer-based event, where _only the head_ of the list needs updating after every opcode.

Improvements:
- 6502 interrupts are now cycle accurate in full-speed (unthrottled) mode (eg. fixes Broadsides, #608)
  - Also FT demos (eg. MAD2) can be toggled full-speed on/of without losing the video/6522 sync.
- The emulation performance is now unaffected by having Mockingboard 6522 timers, as it's not having to update the 4x 6522 timers after every opcode!

Tested with _all_ FT demos (eg. "CHIP" uses 6522-A & 6522-B timer1 interrupts during the video frame, "TRIBU" re-uses the 6522-A timer1 interrupt as it scans down the video frame). Also tested with Dazzle Draw (for Mousecard VBlank).

### CODE REVIEW

**Comment by tomcw** [comment]
Hi Nick / @sicklittlemonkey - can you take a look at this PR if you have time?

The key change is this new linked-list for synchronous events:
https://github.com/AppleWin/AppleWin/blob/GH612-synchronous-events/source/SynchronousEventManager.cpp

This is something we discussed here: https://github.com/AppleWin/AppleWin/issues/612#issuecomment-452173787

The head of the list gets updated after every opcode in the 6502/65C02 switch statement - see the `Update()` function. This replaces the hardcoded calls to Mockingboard & Mousecard to update timers and generate interrupts.

My definition of a synchronous event is for a deterministic event that will occur in N cycles' time, eg. 6522 Timer & Mousecard VBlank. (As opposed to async events, like SSC Rx/Tx interrupts.)

Live events can also be removed - necessary, since 6522 timer events can be started, and then cancelled later, eg. the periodic timer, which generates an interrupt every N cycles. If you change the period, then they need to be removed & re-added.

**Comment by tomcw** [comment]
btw, I realised in the 6502/65C02 opcode switch-statement, that the call to `NTSC_VideoUpdateCycles()` after every opcode, could probably be replaced by a sync event for every video line (65 cycles). This would simplify things in this switch-statement loop. And may improve performance too (`NTSC_VideoUpdateCycles()` called ~21 times per video line to just once).

I'd need to cope with demos that change the video mode across the horizontal line (eg. FT demo ANSI STORY & Sather's Little Text Window), but think this is totally doable too by just splitting up the 65-cycle sync event on a video soft-switch access.

Something to investigate after this PR has been merged in.

**Review by sicklittlemonkey — APPROVED** [review]
Hey, looks good.

Quite an involved change with the mouse SyncEvent handler calling NTSC_GetCyclesUntilVBlank etc. I just skimmed over the MB stuff - trust you there! ; - )

Thinking back to how my mate Sean did this in the past, we managed to optimize away the "if (!pCurrEvent) return;" in SynchronousEventManager::Update by always having at least one sentinel event in the queue - which was the next VBL when we handled it this way. I suppose you could also have a dummy event as a sentinel, but then you decrement the cycles so maybe the null check is cheaper.

The NTSC_VideoUpdateCycles change sounds interesting. It might be faster.

Hmm! Fun stuff!

Cheers,
Nick.

**Comment by tomcw** [comment]
>Thinking back to how my mate Sean did this in the past, we managed to optimize away the "if (!pCurrEvent) return;" in SynchronousEventManager::Update by always having at least one sentinel event in the queue

I suppose if I did get an advantage from doing NTSC video lines updates every 65 cycles, then there would always be an event in the queue, so I could also optimise away the "if (!pCurrEvent) return;".

**Comment by sicklittlemonkey** [comment]
Yeah, I was thinking the same thing. Every little bit helps.

**Comment by fenarinarsa** [comment]
I just saw this PR because I'm merging all recent commits to master into another branch :D

Does it mean that it could be used to easily implement the VSync interrupt of the IIc?

From what I could gather on my actual IIc, the IRQ occurs exactly when VBlank starts, at the end of the visible area of the last displayed line.

Maybe it's the same than for the mousecard Vblank interrupt?

**Comment by tomcw** [comment]
>From what I could gather on my actual IIc, the IRQ occurs exactly when VBlank starts, at the end of the visible area of the last displayed line.

Yes, that's the same as the mousecard's VBlank interrupt.

**Pull request merged**
