### PR TITLE
Replace sprintf() with StrFormat()

### PR DESCRIPTION
**Pull request by kiyolee**
After this, the remaining sprintf() usages *should* all be within the debugger area.

### CODE REVIEW

**Comment by tomcw** [comment]
Can you remove the tfe.cpp changes (but tfearch.cpp is fine to remain), as this will clash with some file renaming (and refactoring) that @audetto is doing in another PR.

After that other PR lands, then you can apply this final patch to the newly named file.

Or perhaps just wait. As if a "git mv" was done on tfe.cpp, then the merge maybe able to resolve it successfully.

**Comment by kiyolee** [comment]
Changes for `tfe.cpp` has been removed.

**Comment by kiyolee** [comment]
Updated the PR to incorporate latest changes. I have put back the original changes for `tfe.cpp` (now in `Uthernet1.cpp`). Please check.

**Comment by tomcw** [comment]
Thanks - merged it now.

**Pull request merged**
