### PR TITLE
Fix for #380 ("Unable to capture PrintScreen key" warning on startup)

### PR DESCRIPTION
**Pull request by kevinmarty**
This is a fix for issue #380 that happens when some other program has already registered the PrintScreen key as a hotkey (OneDrive or the Windows 10 Snip & Sketch tool are common culprits).

I changed the error message in the RegisterHotKeys() function from using the MessageBox() API to using the Windows shlwapi function SHMessageBoxCheck() API, which adds a "Don't show this message again" checkbox to the message.

The GUID in the last parameter is randomly-generated, it is used by the Windows API to store whether the box has been checked in the registry.

### CODE REVIEW

**Comment by tomcw** [comment]
This looks fine to me.

NB. This SHMessageBoxCheck() API is supported on Windows XP and above, so by merging this in, then we need to implicitly state that Win XP is the oldest theoretically "supported" version for AppleWin. Bear in mind that I'm not testing against Win XP, hence why I'm saying "theoretically supported".

**Comment by kevinmarty** [comment]
I changed the code to attempt to dynamically load the SHMessageBoxCheck API and to fall back on using a standard MessageBox if that fails, so this will take care of running on pre-Win XP versions as well.

**Comment by tomcw** [comment]
I've made the change to use v141_xp toolset for AppleWin releases (8d7d2b9647f0fa139444440c924d578f782693a5), which means that Windows XP is the oldest "supported" version. So I will take your initial commit that statically links against shlwapi.lib rather than the newer DLL version.

Can you revert? (perhaps just resubmit your initial change again?) I'll do a 'squash & merge' so it won't matter about these unused changes.

**Comment by kevinmarty** [comment]
Sure, I just removed the commit that added the dynamic linking.

**Comment by tomcw** [comment]
Thanks @kevinmarty - I've merged this to master now.

**Comment by tomcw** [comment]
NB. **SHMessageBoxCheck** records the message boxes that the user has chosen to suppress under the following registry key:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\DontShowMeThisDialogAgain

**Comment by sicklittlemonkey** [comment]
Interesting, I'd never seen this API.

**Pull request merged**
