### PR TITLE
Support to TK3000 //e (Brazilian Apple //e clone)

### PR DESCRIPTION
**Pull request by wmoecke**
Nick kindly pointed out I was posting litter to my branch directory on my previous commit. Hopefully I got my mess cleaned up now.  ;-)
Thanks all!

### CODE REVIEW

**Comment by sicklittlemonkey** [comment]
Hi.

What revision is your new code from?

I see some funky stuff, e.g. here's a small but telling one in memory.cpp:

- $C008   W       ALTZPOFF        Enable main memory from $0000-$01FF & avl
BSR
+ $C008   W       ALZTPOFF        Enable main memory from $0000-$01FF & avl
BSR

Note this is undoing the correcting of the spelling of ALTZPOFF.

Cheers,
Nick.

**Comment by wmoecke** [comment]
Hello, I got my baseline from 1.25.0.4. That code on memory.cpp is not my doing. Nor is anything that has not "TK3000" in it. I'm guessing the baseline I chose has not been taken from 1.25.0.3, or they must had undone that intentionally (for some reason).

**Comment by tomcw** [comment]
>I got my baseline from 1.25.0.4.

That's the problem then. I branched 1.25.0.4 from the 1.25.0.3 release at d1dddbe813826c894be36a3091561290cc08d3d4 (8th Sept 2014). But `master` has moved on (including the typo fix for ALTZPOFF that Nick spotted... this typo was also fixed on 8th Sept, but crucially in a commit **after** 1.25.0.3).

So really we need all your changes applied to a fork of AppleWin from the HEAD of `master`, otherwise we could be faced with a tricky merge with many conflicts.

**Comment by wmoecke** [comment]
Cool. Later on I will pull from the head revision of master and re-do my changes on top of that.
I'm closing this request - Cheerio!

**Comment by wmoecke** [comment]
Hi guys,

Problem: I have checked out from master, created a new branch, and trying
to compile issues me an error:
LNK2001: unresolved external symbol "void __cdecl ConfigureSAM(unsigned
char *,unsigned int)" (?ConfigureSAM@@YAXPAEI@Z)

ConfigureSAM prototype is declared in the header file SAM.h, but I don't
see it implemented anywhere (shouldn't there be a SAM.cpp file somewhere -
assuming it would belong in the /Emulator directory)?

Any clues?

Thanks a lot,
-Werner


 "Success consists of going from failure to failure without loss of
enthusiasm" - Winston Churchill


2015-04-28 10:08 GMT-03:00 TomCh <notifications@github.com>:

**Comment by wmoecke** [comment]
Nevermind.
The file was there, it just wasn't included in the project.

Fixed.


 "Success consists of going from failure to failure without loss of
enthusiasm" - Winston Churchill


2015-04-28 15:40 GMT-03:00 Werner M. <wmoecke@gmail.com>:

**Pull request closed without merging**
