### PR TITLE
Delete unused code from Video.cpp

### PR DESCRIPTION
**Pull request by audetto**
Signed-off-by: Andrea Odetti <mariofutire@gmail.com>

### CODE REVIEW

**Comment by Michaelangel007** [comment]
@audetto Thanks for the patch.  We'll review this.

@tomcw I believe these code snippets can safely be deleted -- if we decide to introduce pre NTSC rendering these won't be needed.

**Comment by Michaelangel007** [comment]
Helper/Reminder -- to test locally ...

```
git checkout -b audetto-cleanup master
git pull https://github.com/audetto/AppleWin.git cleanup
```

**Comment by Michaelangel007** [comment]
@tomcw I've tested this locally and this is good-to-go but I'll hold off merging until you've had a look-see.

**Comment by tomcw** [comment]
@Michaelangel007 - LGTM, so please merge it.

**Pull request merged**
