### PR TITLE
Various *Name() functions can simply return const std::string&

### PR DESCRIPTION
**Pull request by kiyolee**
This saves a bunch of unnecessary string copying.

### CODE REVIEW

**Comment by tomcw** [comment]
This all looks fine, but a minor point, can you add back in the `void` keywords to all the functions' definitions/declarations.
EG. `static const std::string& CpuGetSnapshotStructName(`**`void`**`)`

This will retain the style used by those files.
Admittedly this style isn't consistent within all .cpp files, but whenever I refactor functions or .cpp files, that's what I've been adding.

**Comment by kiyolee** [comment]
I am fine to put those back in. But I think without `void` is more modern C++ style. In C++, `()` strictly means `(void)` whereas in C, `()` is equivalent to `(...)`.

**Comment by tomcw** [comment]
Thanks - yes, put "void" back for now.

We can review the style of using void (or not) another time, involving the other project members.
If it's decided to drop "void" then it can be done wholesale, and documented in the "CodingConventions.txt" file.

**Comment by kiyolee** [comment]
`void` argument lists have been restored.

**Comment by tomcw** [comment]
@kiyolee - after a recent merge, tfe.cpp/h got renamed to Uthernet1.cpp/h.
So can you modify this PR to target those files instead?
Also Uthernet2.cpp/h can be similarly targeted.
Thanks.

**Comment by kiyolee** [comment]
Updated the PR to incorporate latest changes. Please check.

**Comment by tomcw** [comment]
Merged into master - thanks.

**Pull request merged**
