### PR TITLE
Support NSC for Apple II/II+ via F8-ROM

### PR DESCRIPTION
**Pull request by tomcw**
PR for #827.

### CODE REVIEW

**Comment by tomcw** [comment]
I have changed the 6502 (but not the 65C02) emulation so that r/w accesses to $F8xx now supports I/O too, specifically for the NSC.

So 6502 based Apple II's (ie. II, II+, II J-Plus) which all have an F8 Rom (but obviously not a Rom at $C300 / "CD" Rom) can support the NSC.

The 6502 based _unenhanced_ //e will use this 6502 emulation code path too, but since it's a //e it won't support the NSC at F8... and for a //e you'd expect the NSC to be at C3 (ie. the "CD" Rom).

NB. If you were to put a 65C02 into an Apple II/II+/II J-Plus then the NSC at F8 would no longer work, since the I/O support at $F8xx is only added for the 6502 emulation. (Currently the only way to do this is to manually edit the save-state file.)

Why not just support I/O at $F8xx for the 65C02 too? Well it's slightly more code, which could affect performance; also there's no use-case for this (unless you manually edit the save-state file for Apple II's!).

Other performance options are to only support I/O for reads (and not writes) to $F8xx, since currently this is all ProDOS 2.5.0a8 does. But since ProDOS 2.5.0a8 doesn't fully work with the NSC driver, then I consider this a "moving target" so it's safer to start with full support, then consider optimisations once ProDOS 2.5.0's NSC is stable.

**Comment by tomcw** [comment]
Hi Nick / @sicklittlemonkey - FYI, I've created this PR to support NSC for the older (6502-based) Apple II models.

In #827, I've fixed AppleWin to not support the NSC at $C3xx!
So this PR complements that fix, so allow AppleWin to support the NSC at $F8xx. (As supported by ProDOS 2.5.0)

No need to review this PR, but I just wanted to give you a heads-up, since the NSC code is yours.

**Comment by sicklittlemonkey** [comment]
Yeah, when I wrote the code I just chose somewhere that the drivers picked it up IIRC. I see you've logged issues against the ProDOS 2.5 testing repo. Nice one - thanks for all of this.

**Comment by tomcw** [comment]
**UPDATE:** I fixed a bug (26414b7) where LC mode (read ROM / write RAM) wasn't working for II/II+ models with NSC at $F8-ROM.

NB. this bug doesn't exist in any release of AppleWin, as "NSC F8-ROM" support will be added at 1.30.0.0, and this bug was identified and fixed prior to release.

The details are it was flagged by an a2audit test:
- lda c080 ; reset things
- lda c081
- lda c089 ; ROM read, bank 1 write
- inc fe1f ; read $60 from ROM, write $61 to RAM

So in addition to not doing NSC for `HIGHRAM` (LC: r/w RAM), I also exclude `WRITERAM` (LC: r:RAM/w:ROM).

**Pull request merged**
