### PR TITLE
Support 'squaring the circle' for analog sticks

### PR DESCRIPTION
**Pull request by tomcw**
PR for #429 & #1237

### CODE REVIEW

**Comment by tomcw** [comment]
Hi @audetto - here's a PR that integrates your code into the AppleWin mainline.

I want to give you a chance to comment before I merge to the mainline, in case you spot any issue.

**Comment by audetto** [comment]
I won't be able to debug, but I don't see any issue.

What I am a bit concerned about is the following 287 thing.
Have you checked the 2 adjustments still work correctly together?

**Comment by audetto** [comment]
Actually, it can only get better because `coeff>=1`

**Comment by tomcw** [comment]
>Have you checked the 2 adjustments still work correctly together?

They are independent: the first one (square the circle) can give a value of 255 now for both x & y (when in the bottom right position). The the second adjustment (`if (pdlPos >= 255) pdlPos = 287`) will just set x & y both to 287. I tested against the games that need this 287 position, and all work fine (and better than before).

Anyway, it seems like this is fine from your POV, so I'll go ahead and merge it. Thanks.

**Pull request merged**
