### PR TITLE
Use default initializers for local variables

### PR DESCRIPTION
**Pull request by rzumer**
Fixes [type.6 type safety warnings](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-always) (C++ Core Guidelines), generated via code analysis in Visual Studio 2019.

Some of the changes are redundant because instead of default constructors, `Clear()` functions or similar are used to initialize new instances. However the performance cost of using default initializers should be very small, and this ensures that local variables are initialized on instantiation even when they are not handled by the aforementioned clean-up functions.

It is probably OK to remove the calls to the clearing functions from the default constructors that employ them with these changes, but I preferred to err on the side of caution. If all looks good I can amend this PR to remove the calls.

### CODE REVIEW

**Comment by tomcw** [comment]
>Fixes type.6 type safety warnings (C++ Core Guidelines), generated via code analysis in Visual Studio 2019.

That was quick - VS2019 was only released on Tuesday!

This syntax works on VS2015 & VS2017... but AppleWin is still officially built with VS2008, and it doesn't work with this old compiler. So first we need a discussion about moving to a more recent version of VS.

**Comment by rzumer** [comment]
Thanks for checking. That's worth discussing if VS2008 is not critical for supporting certain platforms, but I will try a different approach that is backwards-compatible instead.

**Comment by tomcw** [comment]
>That's worth discussing if VS2008 is not critical for supporting certain platforms

See #559

**Comment by tomcw** [comment]
I don't see the point of adding this C++11 initializer list feature suffix to these areas of the code. IMO, this C++11 syntax is obscure and therefore confusing. So I am rejecting this PR, and will close it.

**Pull request closed without merging**
