### PR TITLE
Prevent uninitialised reads if settings are not present.

### PR DESCRIPTION
**Pull request by audetto**
Signed-off-by: Andrea Odetti <mariofutire@gmail.com>

### CODE REVIEW

**Comment by beevik** [comment]
I'm wondering if there's something preventing the merging of this pull request.  It solves a real crash bug that I was experiencing myself (only in release mode).

(I just noticed this pull request after submitting my larger one -- https://github.com/AppleWin/AppleWin/pull/674).

**Comment by tomcw** [comment]
>I'm wondering if there's something preventing the merging of this pull request. 

Purely a lack of time to review (and other AppleWin-things taking priority).

Is this PR completely covered by your PR #674 ?

**Comment by beevik** [comment]
Yes, my pull request has the same bug fix.

**Comment by tomcw** [comment]
Since this PR is covered by #674, I will close it.

**Pull request closed without merging**
