### PR TITLE
Minor Typo # 2

### PR DESCRIPTION
**Pull request by cbmeeks**
Forgot one from my last pull request.

### CODE REVIEW

**Comment by sicklittlemonkey** [comment]
Just a tip - as GitHub says on your other PR "Add more commits by pushing to the patch-1 branch on cbmeeks/AppleWin" rather than creating multiple trivial related PRs.

Cheers,
Nick.

**Comment by cbmeeks** [comment]
I have no idea what you're talking about.  Where does it say that?  I must be missing something.

**Comment by cbmeeks** [comment]
Never mind.  I see that now.

**Comment by tomcw** [comment]
Committed at eb74c9781782875e091b8bb9bb4188c1926bf55c

**Pull request closed without merging**
