### PR TITLE
Coding Conventions updated

### PR DESCRIPTION
**Pull request by tomcw**
PR for #868.

### CODE REVIEW

**Comment by tomcw** [comment]
@Michaelangel007 - take a look at this PR and let me know what you think?

**Comment by tomcw** [comment]
@Michaelangel007 - are you OK with this PR?
Unless you disagree with my update, then I plan to merge this in at the end of the month (so in just over a week's time).

**Comment by Michaelangel007** [comment]
Sorry, been busy with Nox Archaist & work.  Merged.

**Comment by tomcw** [comment]
Thanks for merging.
btw - Well done with Nox Archaist!

**Pull request merged**
