### PR TITLE
SaveState: add absolute path for disks.

### PR DESCRIPTION
**Pull request by audetto**
https://github.com/AppleWin/AppleWin/issues/1290

### CODE REVIEW

**Review by tomcw — APPROVED** [review]

**Comment by tomcw** [comment]
@audetto - this PR looks fine. Is there anything left to do? Or shall I merge it now?

**Comment by audetto** [comment]
It is good to go.

**Comment by audetto** [comment]
You can merge.

**Comment by tomcw** [comment]
Great - merged it to the main line.

**Pull request merged**
