### PR TITLE
Added new logo for AppleWin emulator

### PR DESCRIPTION
**Pull request by pedgarcia**
As suggested, I am using the Apple's rainbow colour as font background, increased the "emulator for Windows" also adding the ® symbol.

There is also the PSD file, containing all the layers. The font used is "Motter Tektura Cyrilic".

### CODE REVIEW

**Comment by Michaelangel007** [comment]
The logo needs to be pulled for the 1.26 release

**Comment by Michaelangel007** [comment]
GIMP is retarded.  Doesn't under the nested layer masking.
Manually added a layer mask via

1. Duplicate Colors
2. Duplicate Apple ][
3. Select, Save to Channel
4. With Duplicate Colros layer, Add Layer Mask, Channel: Apple ][

**Comment by Michaelangel007** [comment]
http://en.wikipedia.org/wiki/Typography_of_Apple_Inc.

* Motter Tektura

**Comment by Michaelangel007** [comment]
@tomcw @pedgarcia I've created a WIP logo based on this pull request.

image

I've checked in the GIMP source file since 

a) not everyone has Photoshop, and 
b) the original PSD doesn't render properly in Gimp due to Gimp's broken/missing functionality.  

aa119833fab6ad9512861bf394f21d29f7a0819c

**Comment by vgturtle127** [comment]
@Michaelangel007 @tomcw @pedgarcia So has this been added to the project?

**Comment by sicklittlemonkey** [comment]
I've been thinking recently, the buttons could really do with a modern​
makeover.

Cheers,
Nick.

**Comment by tomcw** [comment]
btw. when I merged NTSC_PreMerge branch to master (5fdc879), this updated logo was included.
So I'm closing this pull-request (without merging it).

**Pull request closed without merging**
