### PR TITLE
Improve determining path & filename when saving/loading a save-state

### PR DESCRIPTION
**Pull request by tomcw**
PR for #691.

Be smarter about both the path & filename when saving/loading a state-state file:

On save:
- Filename = (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
  - if still empty, then use last save-state name
  - if still empty, then leave it empty
- Path = (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
  - if still empty, then use last save-state path
  - if still empty, then use `g_sCurrentDir`

On load:
- Filename = last save-state name
  - if empty then (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
  - if still empty, then leave it empty
- Path = last save-state path
  - if still empty, then use `g_sCurrentDir`

### CODE REVIEW

**Comment by Python-Exoproject** [comment]
For load you say:

Filename = last save-state name
Path = last save-state path

Would this be an issue if I run (via command line using an ini for settings) game A, save it, quit, run game B, save it, quit, go back to game A, try to load? The logic says to me in that case it would give me the path and name of game B when what I want is game A?

**Comment by tomcw** [comment]
You're right! ...and you did state this workflow the other month in #691.
NB. the above logic does resolve the original comment when #691 was raised (relating to path shown when pressing F11).

Anyway it seems like a tweak to the above logic to include updating the "last save-state path" on a disk (or harddisk) insertion (both GUI & CUI) should be enough.

**Comment by tomcw** [comment]
Test cases:

- From command line:
  - insert -d1 pathA\A.dsk, save the state (F11) as default (A.aws.yaml) and quit AppleWin
  - insert -d1 pathB\B.dsk
  - save/F11 should offer pathB\B.aws.yaml, then cancel save
  - load/F12  should offer pathB\B.aws.yaml, then cancel load and quit AppleWin

- From GUI:
  - insert (drive-1) pathA\A.dsk, save the state (F11) as A2.aws.yaml and quit AppleWin
  - restart AppleWin
  - save/F11 should offer pathA\A2.aws.yaml, then cancel save
  - load/F12 should offer pathA\A2.aws.yaml, then cancel load and quit AppleWin

- From GUI:
  - insert pathA\A.dsk, save the state (F11) as A2.aws.yaml
  - enable HDD, and plug-in (harddrive-1) pathC\C.2mg, then OK... confirm the emulator restart
  - save/F11 should offer pathC\C.aws.yaml, then cancel save
  - load/F12 should offer pathC\C.aws.yaml, then cancel load
  - disable HDD, then OK... confirm the emulator restart
  - save/F11 should offer pathA\A2.aws.yaml, then cancel save
  - load/F12 should offer pathA\A2.aws.yaml, then cancel save and quit AppleWin

**Comment by tomcw** [comment]
New logic...

On any harddisk or disk insertion (eg. from command line, GUI or save-state):
- Path & Filename = (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
- if path is same as current save-state path then do nothing
  - eg. this is for when the user isn't using the default save-state name
- else set new save-state's path & filename

When saving/loading a state-state file (NB. treat saving & loading the same)
- path = save-state's path
  - if still empty, then use `g_sCurrentDir`
- file = save-state's filename
- on a successful save or load of a save-state then:
  - set new save-state's path & filename
  - save this pathname to Registry (or conf.ini)

Let me attach a pre-release build of AppleWin so you can test it (coming in the next comment)...

**Comment by tomcw** [comment]
@Python-Exoproject , @exoscoriae: here's a pre-release build: [Applewin1.29.14.1.zip](https://github.com/AppleWin/AppleWin/files/5433467/Applewin1.29.14.1.zip)
Please test this build (just unzip over the top of your 1.29.14.0 AppleWin folder), and let me know if it works for your cases.

**Comment by Python-Exoproject** [comment]
I get this small issue when using "load game". The default load name is just the last 6 characters of my image name (Game disk image is called "2400 A.D. (1988) side A.dsk"). If I then click out of the AppleWin window and back into the window the name updates with the full image name.

image

Other than that, as far as I can tell from my testing its all good!

**Comment by Python-Exoproject** [comment]
Just as a side question is there a way to deal with the last floppy that was booted still being listed when the next game is a hard drive game? I.E. In the below image a hard disk image with "Eamon" was booted, but the last game loaded was the floppy of "Choplifter!". You can still see the "Choplifter!" image is loaded into the disk 1 slot. Its not a big deal, and doesnt cause any problems playing, just wondering if there is a command line argument I havent noticed that might remove it when loading the hard disk game.

image

**Comment by tomcw** [comment]
>I get this small issue when using "load game".

I noticed this too. The full filename is there, but only the end part is displayed.
Searching, it appears to be a Win32 API bug:
https://community.intel.com/t5/Intel-Fortran-Compiler/GetOpenFileName-default-file-display-problem/td-p/1107308

EG. Press the "Home" key or Control+Left Arrow to reveal the name from the beginning.

NB. This is the same behaviour as in previous versions of AppleWin... so not a regression.

**Comment by Python-Exoproject** [comment]
Ah, your right. All good then, its working as expected. Thank you very much for your assistance on all of this Tom.

**Comment by tomcw** [comment]
>As an aside to the issue above, is there a way to deal with the last floppy that was booted still being listed when the next game is a hard drive game?

Two ways that I can think of:

1. applewin.exe -d1 ""
   - but this shows an warning message box ("Failed to insert floppy disk(s) - see log file") that the user has to click OK.
2. applewin.exe -s6 empty
   - this removes the floppy controller from slot-6. It is a temporary thing, and doesn't persist the state to the Registry. But it means that since there's no floppy controller, then no floppies can be inserted during this AppleWin session.

I will improve (1) such that -d1 "" (or -d2,-h1,-h2 "", etc) eject/unplug the disk/harddisk without any msg box.

**Comment by Python-Exoproject** [comment]
Much appreciated

**Pull request merged**
