### PR TITLE
Convert files with special characters to UTF-8

### PR DESCRIPTION
**Pull request by rzumer**
Compilation fails on some of these files on computers with certain locales (e.g. CJK) otherwise.

### CODE REVIEW

**Comment by rzumer** [comment]
There are a few conversion errors, please hold.

**Comment by rzumer** [comment]
Any comment on this? It is needed to display and in some cases compile depending on the system locale.

**Comment by rzumer** [comment]
As it turns out, explicit UTF-8 compilation is required for me to compile at all, so I have added that to my PR as well.

```
6>ParallelPrinter.cpp
6>c:\users\rzumer\projects\applewin\source\parallelprinter.cpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
6>c:\users\rzumer\projects\applewin\source\parallelprinter.cpp(165): error C2001: newline in constant
6>c:\users\rzumer\projects\applewin\source\parallelprinter.cpp(166): error C2144: syntax error: 'char' should be preceded by ';'
```

**Comment by rzumer** [comment]
@tomcw Can you please review this?

**Comment by tomcw** [comment]
@rzumer - sorry, I meant to look at this a while ago. Anyway, merged in now. Thanks for the PR.

**Pull request merged**
