### PR TITLE
CPU emulation timing fixes

### PR DESCRIPTION
**Pull request by tomcw**
Take a look or review this pull request before I merge to master in a few days:
- Fixes for these issues: #264, #271, #278, #282, #288.
- Some refactoring (splitting & renaming of macros).
- Added unit tests for all these fixes (maybe I should hook it up so that it always runs at the end of the AppleWin build).

Should we delete the cpu65d02.h code for now? It's not used by anything, and just adds cost to any changes/fixes made to the 6502/65C02 emulation code. Since it's not used or tested then there's no way to know about its correctness.

### CODE REVIEW

**Comment by Michaelangel007** [comment]
No, leave cpu65d02.h -- I can fix it up later.

It will eventually be the 6502 memory visualizer. i.e. A 256x256 bitmap that represents the 64K memory access. R = write, G = read, B = exec.

**Comment by Michaelangel007** [comment]
This patch looks mostly great.

However, I do have some feedback.  

1. Why are the  mnemonics increased from 3 chars?

		case 0x7C: $ ABSX_OPT NOP	CYC(4)  break;
		case 0x7D:   ABSX_OPT ADCn	CYC(4)  break;
		case 0x7E:   ABSX_CONST RORn	CYC(6)  break;
		case 0x7F: $ ABSX_CONST 

2. Why is the column alignment not being preserved ?

		case 0x38:       SEC	CYC(2)  break;
		case 0x39:   ABSY_OPT AND	CYC(4)  break;
		case 0x3A: $     NOP	CYC(2)  break;
		case 0x3B: $ ABSY_CONST RLA	CYC(7)  break; // invalid

Before the CPU/cpu65?02.h files are changed, I'll post another comment on the course of action.

**Comment by Michaelangel007** [comment]
This is a list of the opcodes updated using the new mneomics

    case 0x11:   INDY_OPT   ORA     CYC(5)  break;
    case 0x19:   ABSY_OPT   ORA     CYC(4)  break;
    case 0x1D:   ABSX_OPT   ORA     CYC(4)  break;
    case 0x1E:   ABSX_OPT   ASLc    CYC(6)  break;
    case 0x31:   INDY_OPT   AND     CYC(5)  break;
    case 0x39:   ABSY_OPT   AND     CYC(4)  break;
    case 0x3C:   ABSX_OPT   BIT     CYC(4)  break;
    case 0x3D:   ABSX_OPT   AND     CYC(4)  break;
    case 0x3E:   ABSX_OPT   ROLc    CYC(6)  break;
    case 0x51:   INDY_OPT   EOR     CYC(5)  break;
    case 0x59:   ABSY_OPT   EOR     CYC(4)  break;
    case 0x5C: $ ABSX_OPT   NOP     CYC(8)  break;
    case 0x5D:   ABSX_OPT   EOR     CYC(4)  break;
    case 0x5E:   ABSX_OPT   LSRc    CYC(6)  break;
    case 0x6C:   IABSCMOS   JMP     CYC(6)  break;
    case 0x71:   INDY_OPT   ADCc    CYC(5)  break;
    case 0x79:   ABSY_OPT   ADCc    CYC(4)  break;
    case 0x7C:   IABSX      JMP     CYC(6)  break;
    case 0x7D:   ABSX_OPT   ADCc    CYC(4)  break;
    case 0x7E:   ABSX_OPT   RORc    CYC(6)  break;
    case 0x91:   INDY_CONST STA     CYC(6)  break;
    case 0x99:   ABSY_CONST STA     CYC(5)  break;
    case 0x9C:   ABS        STZ     CYC(4)  break;
    case 0x9D:   ABSX_CONST STA     CYC(5)  break;
    case 0x9E:   ABSX_CONST STZ     CYC(5)  break;
    case 0xB1:   INDY_OPT   LDA     CYC(5)  break;
    case 0xB9:   ABSY_OPT   LDA     CYC(4)  break;
    case 0xBC:   ABSX_OPT   LDY     CYC(4)  break;
    case 0xBD:   ABSX_OPT   LDA     CYC(4)  break;
    case 0xBE:   ABSY_OPT   LDX     CYC(4)  break;
    case 0xD1:   INDY_OPT   CMP     CYC(5)  break;
    case 0xD9:   ABSY_OPT   CMP     CYC(4)  break;
    case 0xDC: $ ABSX_OPT   NOP     CYC(4)  break;
    case 0xDD:   ABSX_OPT   CMP     CYC(4)  break;
    case 0xDE:   ABSX_CONST DEC     CYC(7)  break;
    case 0xF1:   INDY_OPT   SBCc    CYC(5)  break;
    case 0xF9:   ABSY_OPT   SBCc    CYC(4)  break;
    case 0xFC: $ ABSX_OPT   NOP     CYC(4)  break;
    case 0xFD:   ABSX_OPT   SBCc    CYC(4)  break;
    case 0xFE:   ABSX_CONST INC     CYC(7)  break;

**Comment by Michaelangel007** [comment]
This is a list of the updated opcodes that are using the new mnemonics -- I've also aligned this list for readability.

    case 0x11:   INDY_OPT   ORA     CYC(5)  break;
    case 0x19:   ABSY_OPT   ORA     CYC(4)  break;
    case 0x1D:   ABSX_OPT   ORA     CYC(4)  break;
    case 0x1E:   ABSX_OPT   ASLc    CYC(6)  break;
    case 0x31:   INDY_OPT   AND     CYC(5)  break;
    case 0x39:   ABSY_OPT   AND     CYC(4)  break;
    case 0x3C:   ABSX_OPT   BIT     CYC(4)  break;
    case 0x3D:   ABSX_OPT   AND     CYC(4)  break;
    case 0x3E:   ABSX_OPT   ROLc    CYC(6)  break;
    case 0x51:   INDY_OPT   EOR     CYC(5)  break;
    case 0x59:   ABSY_OPT   EOR     CYC(4)  break;
    case 0x5C: $ ABSX_OPT   NOP     CYC(8)  break;
    case 0x5D:   ABSX_OPT   EOR     CYC(4)  break;
    case 0x5E:   ABSX_OPT   LSRc    CYC(6)  break;
    case 0x6C:   IABSCMOS   JMP     CYC(6)  break;
    case 0x71:   INDY_OPT   ADCc    CYC(5)  break;
    case 0x79:   ABSY_OPT   ADCc    CYC(4)  break;
    case 0x7C:   IABSX      JMP     CYC(6)  break;
    case 0x7D:   ABSX_OPT   ADCc    CYC(4)  break;
    case 0x7E:   ABSX_OPT   RORc    CYC(6)  break;
    case 0x91:   INDY_CONST STA     CYC(6)  break;
    case 0x99:   ABSY_CONST STA     CYC(5)  break;
    case 0x9C:   ABS        STZ     CYC(4)  break;
    case 0x9D:   ABSX_CONST STA     CYC(5)  break;
    case 0x9E:   ABSX_CONST STZ     CYC(5)  break;
    case 0xB1:   INDY_OPT   LDA     CYC(5)  break;
    case 0xB9:   ABSY_OPT   LDA     CYC(4)  break;
    case 0xBC:   ABSX_OPT   LDY     CYC(4)  break;
    case 0xBD:   ABSX_OPT   LDA     CYC(4)  break;
    case 0xBE:   ABSY_OPT   LDX     CYC(4)  break;
    case 0xD1:   INDY_OPT   CMP     CYC(5)  break;
    case 0xD9:   ABSY_OPT   CMP     CYC(4)  break;
    case 0xDC: $ ABSX_OPT   NOP     CYC(4)  break;
    case 0xDD:   ABSX_OPT   CMP     CYC(4)  break;
    case 0xDE:   ABSX_CONST DEC     CYC(7)  break;
    case 0xF1:   INDY_OPT   SBCc    CYC(5)  break;
    case 0xF9:   ABSY_OPT   SBCc    CYC(4)  break;
    case 0xFC: $ ABSX_OPT   NOP     CYC(4)  break;
    case 0xFD:   ABSX_OPT   SBCc    CYC(4)  break;
    case 0xFE:   ABSX_CONST INC     CYC(7)  break;

Regarding the points (1) and (2) I raised early ...

(1) Ideally I would like to see the new mnemonics use 3 or 4 characters but I can let this slide for now.

Here is a list of new mnemonics being added; I've added a recommended new mnemonics. I also propose a leading underscore as a visual way to indicate that they are not "proper" mnemonics.  (We could also use a trailing underscore.)

    ABSX_CONST | _AXC
    ABSX_OPT   | _AXO
    ABSY_CONST | _AYC
    ABSY_OPT   | _AYO
    IABSCMOS   | _IA
    IABSX      | _IAX
    INDY_CONST | _IYC
    INDY_OPT   | _IYO

NOTE: we are using uppercase for documented instructions, lowercase for undocumented instructions.  I believe it is important to be able to see this 3rd case.

Another idea would be to replace the bulku _CONST and _OPT with _C and _V respectively.  The _C for constant, and _V for variable. My concern is that _C would imply carry but hopefully it is clear enough from examples like `RORc`

(2) We should at the very least fix the column alignment before accepting this patch.

At some point we probably should replace all the tabs mid-line with spaces so we don't have multiple tabs OR convert everything over to tabs 

This begs the question: Tabs or Spaces? Doesn't matter as long as we are consistent.

Sorry to nitpick but I believe it is better to nip this in the bud while everything is still fresh and keep the readability.

**Comment by Michaelangel007** [comment]
I'm assuming the long mnemonics came from this table over in bug #271 ?

https://cloud.githubusercontent.com/assets/1569787/7407371/54297cd8-eedf-11e4-99e9-120cd9d08003.png

**Comment by Michaelangel007** [comment]
Sorry, replaced the incorrect ~~mnemonics~~ with the correct `addressing modes` term.

**Comment by tomcw** [comment]
Hi Michael, thanks for taking the time to look and add your comments.

>No, leave cpu65d02.h please 

OK.

>1.Why are the addressing modes increased from 3 chars?

3 chars wasn't enough to meaningfully describe things.
But to be honest I don't think either of these are that readable either:
- `case 0x11:   IYO_  ORA     CYC(5)  break;`
- `case 0x11:   IYo   ORA     CYC(5)  break;`

Why not go with a more verbose `INDY_OPT   ORA`? (but with consistent alignment for all opcodes)

>2.Why is the column alignment not being preserved ?

I didn't want to fix the alignment until I'd had some feedback. I will reformat the white-space to correctly space macros for all opcodes.

>We should at the very least fix the column alignment before accepting this patch.

I agree.

>At some point we probably should replace all the tabs mid-line with spaces...

I agree.

>I noticed 0x6C was modified for 6502 for CYC(5) to but not 65c02 CYC(6)

Right: 6502 is 5, but 65C02 is 6 cycles (see 6502 timings I #264 and 65C02 timings in #271).

>Sorry to nitpick...

On the contrary, I appreciate your thoughts. This is your code after all! :)

BTW. I plan to add unit tests for all opcodes (both 6502 & 65C02) to check their timings (for both non- and page-crossing variants where applicable & the 3 variants for Bcc opcodes). I will do this before any merge.

**Comment by Michaelangel007** [comment]
Upon further reflection, you know, I think you're right Tom; this is probably one of the times when we should be more verbose instead of abbreviating since we don't lose anything; abbreviating it just doesn't add anything -- it has the exact opposite effect -- it takes away from clarity.

I would be very happy with this patch with the long addressing mode names once the alignment is fixed. :-)

> On the contrary, I appreciate your thoughts. This is your code after all! :)

Well, I can't take _all_ the credit -- I just help maintain it. :-)

Thanks for the open dialogue about this patch Tom -- when I submitted my feedback I wasn't sure how it would be received. I'm really glad we are on the same page with minimal amount of changes. =)

**Comment by Michaelangel007** [comment]
> Right: 6502 is 5, but 65C02 is 6 cycles (see 6502 timings I #264 and 65C02 timings in #271).

Ah, gotcha.  Doesn't hurt to double check :+1:

**Comment by sicklittlemonkey** [comment]
Ah, last millennium. Well do I remember naming abbreviations like NUM, STR,
PTR, HDL ...

My 2c is that those should stay in that millennium. These days we have big
screens, plenty of columns, gigabytes of memory, and auto-completion.

Make things readable. And of course, use spaces, not tabs. ; - )

Great work Tom!

Cheers,
Nick.

**Comment by tomcw** [comment]
OK, I've corrected the alignment in the switch statements (and replaced tabs with spaces, except for the initial tab indentations for those 256 lines). I've also made it so that the 6502/65C02 unit tests run as a pre-build event before AppleWin gets built (but just in the VS2008 sln/proj at the moment).

I will merge to master tomorrow unless anyone has any other comments.

**Comment by Michaelangel007** [comment]
Sorry, posted comment in #288 instead of here ...

Thanks for taking the initiative on the Great Whitespace Cleanup Tom!  Much appreciated. :-)

I've synced up 65d02.h to all your change in 65C02.h so I'm thinking we're looking pretty good.  This patch is almost ready sans one question:

Could you clarify why all the // invalid" was removed in commit  https://github.com/AppleWin/AppleWin/commit/df5635dc111752194a60df4f760a80f6a591dce8 please? Thanks

        case 0x07: $ ZPG ASO	CYC(5)  break; // invalid

The // invalid was a nice marker for all the invalid opcodes in 6502 ...

**Comment by tomcw** [comment]
Hi Michael,

>Could you clarify why all the // invalid" was removed ...

Isn't `$` a macro used for invalid 6502 opcodes? If there's a difference, then I can restore those comments. 

Also the `// invalid` comments don't look complete, eg. opcode 0xFF is an invalid opcode INS, but it doesn't have the comment.

**Comment by Michaelangel007** [comment]
I think you're right Tom.  Hmm, looks like the comments were out of date then, since as you point out, there are opcodes with `$` but without `invalid`

i.e.

        case 0x02: $     HLT	CYC(2)  break;		
        case 0x03: $ idx ASO	CYC(8)  break;		
        case 0x04: $ ZPG NOP	CYC(3)  break;	

Alright, no more objections to this patch. :-) :+1:

**Pull request merged**
