### PR TITLE
Added support to TK3000 //e (Brazilian Apple //e clone)

### PR DESCRIPTION
**Pull request by wmoecke**
Added Menus/ROM/"Run" Button.
Also included firmware ROM to support future emulation of the TKClock board (Timemaster II H.O. clone by Applied Engineering).

** Bunch of files listed as being added by me - not true at all:
RESOURCE\LED_CAPS_OFF.BMP
RESOURCE\LED_CAPS_OFF_LAT.BMP
RESOURCE\LED_CAPS_OFF_P8.BMP
RESOURCE\LED_CAPS_ON.BMP
RESOURCE\LED_CAPS_ON_LAT.BMP
RESOURCE\LED_CAPS_ON_P8.BMP
RESOURCE\Pravets8M.rom
RESOURCE\ROM1.BIN
RESOURCE\ROM2.BIN

** Files added by me in this commit:
resource\RUN3000E.bmp
resource\TK3000e.rom
resource\TKClock.rom

** Included missing SAM.cpp file in project as well. Linker error.
** Also, be aware the resource.h is shown with lots of defines "removed, then re-added". Kinda misleading.

As the man with the axe used to say - "Here's Johnny!"

### CODE REVIEW

**Comment by sicklittlemonkey** [comment]
Cool. That's a reassuringly short change list. ; - )

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
Did we want to punt on this PR until after 1.26 ?

**Comment by tomcw** [comment]
Merged to master at 2d61c7.
I need to track outstanding TK3000 //e work in a new issue.

**Comment by tomcw** [comment]
Created #367 to track outstanding to-do's etc.

@wmoecke: can you give more details about this code comment (Keyboard.cpp)?
> VideoRedrawScreen();  // TODO: Still need to implement page mode switching and 'whatnot'

**Pull request closed without merging**
