### PR TITLE
Fix for issue #323 (can't bypass hard drive boot)

### PR DESCRIPTION
**Pull request by rhoem1**
I added a check against open-apple, if pressed, the firmware will direct the boot to slot 6.

Toyed with the idea of using a timeout loop. Decided to go with just a simple check.

### CODE REVIEW

**Comment by tomcw** [comment]
Hi Robert,
Did you mean to close this pull request? (If so, why?)

**Comment by rhoem1** [comment]
That branch became a mess.  I'd like to redo it.

**Comment by rhoem1** [comment]
Basically, the branch should have just the changes to hddrvr.a65 and
updates to hddrvr.bin.   Somehow the code I put together to fix that "can't
mount the hard disk" bug got added to that branch, and I certainly do not
want to pollute things with unneeded code.  I noticed that the PR hadn't
been updated yet, so I decided to pull it and recreate the PR and branch.

**Comment by tomcw** [comment]
OK, thanks for the info. Looking forward to the new PR.

**Pull request closed without merging**
